# Generated by Django 4.0.4 on 2023-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_donated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
